services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        restart: always

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: kso_modular
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always

    loki:
        image: grafana/loki:latest
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - loki-data:/loki
        restart: always

    promtail:
        image: grafana/promtail:latest
        volumes:
            - /var/log:/var/log
            - ./promtail-config.yml:/etc/promtail/config.yml
        command: -config.file=/etc/promtail/config.yml
        depends_on:
            - loki
        restart: always

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - grafana-data:/var/lib/grafana
        depends_on:
            - loki
        restart: always

    minio:
        image: minio/minio:latest
        container_name: minio
        command: server --console-address ":9001" /data/
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
            MINIO_SERVER_URL: 'http://192.168.0.99'
        volumes:
            - minio-data:/data
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://192.168.0.99:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

volumes:
    postgres_data:
    loki-data:
    grafana-data:
    minio-data:
