available_attributes = [
    'AboutBox', 'ActivizationControlByte', 'ActivizationStatus', 'AddLD', 'AdjustRITimeout', 'AdminUnlockPort',
    'AdminUnlockPorts', 'Annulment', 'AnnulmentRB', 'AnswerCode', 'AttributeNumber', 'AttributeValue', 'AuthData',
    'Authorization', 'AutoOpenSession', 'AutoSensorValues', 'AutoStartSearch', 'BC1D_Code128A', 'BC1D_Code128B',
    'BC1D_Code128C', 'BC1D_Code39', 'BC1D_EAN13', 'BC1D_ReservedForQR', 'BC2D_AZTEC', 'BC2D_DATAMATRIX', 'BC2D_PDF417',
    'BC2D_QRCODE', 'BCT_Above', 'BCT_Below', 'BCT_Both', 'BCT_None', 'BanknoteCount', 'BanknoteType', 'BarCode',
    'BarWidth', 'BarcodeAlignment', 'BarcodeDataLength', 'BarcodeFirstLine', 'BarcodeHex', 'BarcodeParameter1',
    'BarcodeParameter2', 'BarcodeParameter3', 'BarcodeParameter4', 'BarcodeParameter5', 'BarcodeStartBlockNumber',
    'BarcodeType', 'BatteryVoltage', 'BaudRate', 'Beep', 'BeginDocument', 'BinaryConversion', 'BlockData',
    'BlockDataHex', 'BlockNumber', 'BlockType', 'BufferingType', 'Buy', 'BuyEx', 'CalculationSign', 'CancelCheck',
    'CapGetShortECRStatus', 'CardPayProperties', 'CarryStrings', 'CashAcceptorPollingMode', 'CashAcceptorReport',
    'CashControlClose', 'CashControlEnabled', 'CashControlHost', 'CashControlOpen', 'CashControlPassword',
    'CashControlPort', 'CashControlProtocols', 'CashControlUseTCP', 'CashIncome', 'CashOutcome', 'CenterImage',
    'Change', 'ChangeFont', 'ChangeOffset', 'ChangeProtocol', 'ChangeStringNumber', 'ChangeSumFont', 'ChangeSumOffset',
    'ChangeSymbolNumber', 'CharHeight', 'CharWidth', 'Charge', 'ChargeOnSlipDocument', 'ChargeValue', 'CheckConnection',
    'CheckEJConnection', 'CheckFM', 'CheckFMConnection', 'CheckItemLocalError', 'CheckItemLocalResult', 'CheckItemMode',
    'CheckSubTotal', 'CheckSum', 'CheckType', 'CheckingType', 'ClearPrintBuffer', 'ClearReportBuffer', 'ClearResult',
    'ClearSlipDocumentBuffer', 'ClearSlipDocumentBufferString', 'ClicheFont', 'ClicheOffset', 'ClicheStringNumber',
    'CloseCheck', 'CloseCheckBel', 'CloseCheckEx', 'CloseCheckOnSlipDocument', 'CloseCheckWithKPK', 'CloseCheckWithResult',
    'CloseEKLZArchive', 'CloseNonFiscalDocument', 'CloseScreen', 'CloudCashdeskEnabled', 'CodePage', 'ComNumber',
    'CommandCode', 'CommandCount', 'CommandDefTimeout', 'CommandIndex', 'CommandName', 'CommandRetryCount', 'CommandTimeout',
    'ComputerName', 'ConfigureGeneralSlipDocument', 'ConfigureSlipDocument', 'ConfigureStandardSlipDocument', 'ConfirmDate',
    'Connect', 'Connect2', 'Connected', 'ConnectionTimeout', 'ConnectionType', 'ConnectionURI', 'ContentsOfCashRegister',
    'ContentsOfOperationRegister', 'ContinuePrint', 'CopyOffset1', 'CopyOffset2', 'CopyOffset3', 'CopyOffset4', 'CopyOffset5',
    'CopyType', 'Correction', 'CorrectionType', 'CrptCdnListUrl', 'CrptCheck', 'CrptExchangeCaCertPath', 'CrptToken',
    'CustomerCode', 'CustomerEmail', 'CutCheck', 'CutType', 'DBDocType', 'DBFilePath', 'DBFindDocument', 'DBGetNextDocument',
    'DBPrintDocument', 'DBPrintNextDocument', 'DBQueryDocumentsInSession', 'DFE_AutoReadDetailedErrorDescription', 'DFE_BlockingMode',
    'DFE_DataPresentation', 'DFE_PlainTransfer', 'DFE_SkipAllPrinting', 'DFE_SkipRequisitePrint', 'DFE_UseDefaultPropertyIfNotSetByUser',
    'DPE_BluetoothTableNumber', 'DPE_DefaultAdminPassword', 'DPE_DefaultTaxPassword', 'DPE_EmbeddedTableNumber', 'DPE_FFDVersionFieldNumber',
    'DPE_FFDVersionTableNumber', 'DPE_FirstDrawLine', 'DPE_Font1Width', 'DPE_Font2Width', 'DPE_FsTableNumber', 'DPE_InnDigitCount',
    'DPE_LongRnmDigitCount', 'DPE_LongSerialDigitCount', 'DPE_MaxCmdLength', 'DPE_MaxDrawLineCount512', 'DPE_MaxDrawLineWidth',
    'DPE_MaxDrawLineWidth512', 'DPE_OfdTableNmb', 'DPE_RnmDigitCount', 'DPE_TaxFieldNumber', 'DPE_f00_journal_weight_sensor',
    'DPE_f01_receipt_weight_sensor', 'DPE_f02_journal_opt_sensor', 'DPE_f03_receipt_opt_sensor', 'DPE_f04_cover_sensor', 'DPE_f05_journal_lever',
    'DPE_f06_receipt_lever', 'DPE_f07_hi_slip_sensor', 'DPE_f08_low_slip_sensor', 'DPE_f09_presenter', 'DPE_f10_presenter_commands',
    'DPE_f11_ej_overflow_flag', 'DPE_f12_ej', 'DPE_f13_cutter', 'DPE_f14_drawer_status_as_presenter_paper_sensor', 'DPE_f15_drawer_sensor',
    'DPE_f16_presenter_in_paper_sensor', 'DPE_f17_presenter_out_paper_sensor', 'DPE_f18_bill_acceptor', 'DPE_f19_tax_keyboard',
    'DPE_f20_journal', 'DPE_f21_slip', 'DPE_f22_non_fiscal_doc_commands', 'DPE_f23_cashcore', 'DPE_f24_inn_leading_zeros', 'DPE_f25_rnm_leading_zeros',
    'DPE_f26_line_printing_bytes_swapping', 'DPE_f27_wrong_tax_password_blocking', 'DPE_f28_alt_protocol', 'DPE_f29_string_printing_commands_wrap_strings_by_n',
    'DPE_f30_string_printing_commands_wrap_strings_by_font', 'DPE_f31_fisc_commands_wrap_strings_by_n', 'DPE_f32_fisc_commands_wrap_strings_by_font',
    'DPE_f33_senior_cashier', 'DPE_f34_slip_receipt_bit3', 'DPE_f35_block_graphic_loading', 'DPE_f36_error_description_command', 'DPE_f37_print_flags_for_print_ext_graphics_print_line',
    'DPE_f38_skno', 'DPE_f39_mfp', 'DPE_f40_ej5', 'DPE_f41_print_scaled_graphics', 'DPE_f42_print_ext_graphics_512', 'DPE_f43_fs', 'DPE_f44_eod', 'DPE_f45_tag_autoprint_support',
    'DPE_f46_qr_in_footer_support', 'DPE_f47_fs_1_1_support', 'DPE_f48_correction_new_support', 'DPE_f49_error_description_command_extended', 'DPE_f50_fd_answers_extended',
    'DPE_f51_fd_authorization_req', 'DPE_f52_plain_protocolv1_transfer', 'DPE_f53_blocking_mode_available', 'DPE_reserved', 'DPF_ClassicJson', 'DPF_ClassicText', 'DampRequest',
    'DataBlock', 'DataBlockHex', 'DataBlockNumber', 'DataBlockSize', 'DataLength', 'DataOffset', 'Date', 'Date2', 'DeclarativeEndpointPath', 'DeclarativeInput', 'DeclarativeOutput',
    'DecodeTLVData', 'DelayedPrint', 'DeleteLD', 'Denominator', 'Department', 'DepartmentFont', 'DepartmentOffset', 'DepartmentStringNumber', 'DepartmentSymbolNumber', 'DeviceCode',
    'DeviceCodeDescription', 'DeviceFunctionNumber', 'DigitalSign', 'Disconnect', 'Discount', 'Discount1', 'Discount2', 'Discount3', 'Discount4', 'DiscountOnCheck', 'DiscountOnCheckFont',
    'DiscountOnCheckOffset', 'DiscountOnCheckStringNumber', 'DiscountOnCheckSumFont', 'DiscountOnCheckSumOffset', 'DiscountOnCheckSumSymbolNumber', 'DiscountOnCheckSymbolNumber',
    'DiscountOnSlipDocument', 'DiscountValue', 'DivisionalQuantity', 'DoNotSendENQ', 'DocumentCount', 'DocumentName', 'DocumentNumber', 'DocumentSize', 'DocumentType', 'DozeOilCheck',
    'Draw', 'DrawEx', 'DrawScale', 'DrawerNumber', 'DriverBuild', 'DriverMajorVersion', 'DriverMinorVersion', 'DriverRelease', 'DriverVersion', 'ECRAdvancedMode', 'ECRAdvancedModeDescription',
    'ECRBuild', 'ECRDate', 'ECRFlags', 'ECRID', 'ECRInput', 'ECRMode', 'ECRMode8Status', 'ECRModeDescription', 'ECRModeStatus', 'ECROutput', 'ECRSoftDate', 'ECRSoftVersion', 'ECRTime',
    'EKLZActivization', 'EKLZActivizationResult', 'EKLZData', 'EKLZDepartmentReportInDatesRange', 'EKLZDepartmentReportInSessionsRange', 'EKLZFlags', 'EKLZFont', 'EKLZInterrupt',
    'EKLZIsPresent', 'EKLZJournalOnSessionNumber', 'EKLZNumber', 'EKLZOffset', 'EKLZResultCode', 'EKLZSessionReportInDatesRange', 'EKLZSessionReportInSessionsRange', 'EKLZSessionTotal',
    'EKLZVersion', 'EjectDirection', 'EjectSlipDocument', 'EnableCashcoreMarkCompatibility', 'EndDocument', 'EnumLD', 'ErrorCode', 'ErrorDescription', 'EscapeIP', 'EscapePort', 'EscapeTimeout',
    'ExchangeBytes', 'ExcisableOperation', 'ExciseCode', 'ExportTables', 'FM1IsPresent', 'FM2IsPresent', 'FMBuild', 'FMFlags', 'FMFlagsEx', 'FMMode', 'FMOffset', 'FMOverflow', 'FMResultCode',
    'FMSoftDate', 'FMSoftVersion', 'FMStringNumber', 'FN30DayResource', 'FN5YearResource', 'FNAcceptMakringCode', 'FNAcceptMarkingCode', 'FNAddTag', 'FNArchiveType', 'FNBeginCalculationStateReport',
    'FNBeginCloseFiscalMode', 'FNBeginCloseSession', 'FNBeginCorrectionReceipt', 'FNBeginFiscalization', 'FNBeginOpenSession', 'FNBeginReadArchive', 'FNBeginReadNotifications', 'FNBeginRegistrationReport',
    'FNBeginSTLVTag', 'FNBindMarkingItem', 'FNBuildCalculationStateReport', 'FNBuildCorrectionReceipt', 'FNBuildCorrectionReceipt2', 'FNBuildRegistrationReport', 'FNBuildReregistrationReport',
    'FNCancelDocument', 'FNCheckItemBarcode', 'FNCheckItemBarcode2', 'FNCheckItemBarcodeCrpt', 'FNCloseCheckEx', 'FNCloseFiscalMode', 'FNCloseSession', 'FNConfirmNotificationRead', 'FNCountersSync',
    'FNCurrentDocument', 'FNDeclineMarkingCode', 'FNDiscountChargeRN', 'FNDiscountOperation', 'FNDiscountTaxOperation', 'FNDocumentData', 'FNFindDocument', 'FNFiscalization', 'FNGetCurrentSessionParams',
    'FNGetDocumentAsString', 'FNGetDocumentSize', 'FNGetExpirationTime', 'FNGetFiscalizationResult', 'FNGetFiscalizationResultByNumber', 'FNGetFreeMemoryResource', 'FNGetImplementation', 'FNGetInfoExchangeStatus',
    'FNGetKMServerExchangeStatus', 'FNGetMarkingCodeWorkStatus', 'FNGetNonClearableSumm', 'FNGetOFDTicketByDocNumber', 'FNGetOSUSupportStatus', 'FNGetSerial', 'FNGetStatus', 'FNGetTagDescription', 'FNGetUnconfirmedDocCount',
    'FNGetVersion', 'FNImplementation', 'FNLifeState', 'FNMarkingClearBuffer', 'FNOSUSupportStatus', 'FNOpenCheckCorrection', 'FNOpenSession', 'FNOperation', 'FNPrintDocument', 'FNPrintOperatorConfirm', 'FNReadArchiveItem',
    'FNReadFiscalBarcode', 'FNReadFiscalDocumentTLV', 'FNReadNotificationBlock', 'FNRequestFiscalDocumentTLV', 'FNRequestRegistrationTLV', 'FNResetState', 'FNSaveArchive', 'FNSendCustomerEmail', 'FNSendItemBarcode',
    'FNSendItemCodeData', 'FNSendSTLVTag', 'FNSendSTLVTagOperation', 'FNSendSenderEmail', 'FNSendTLV', 'FNSendTLVOperation', 'FNSendTag', 'FNSendTagOperation', 'FNSendUserAttribute', 'FNSessionState', 'FNSoftType',
    'FNSoftVersion', 'FNStorno', 'FNWarningFlags', 'FeedAfterCut', 'FeedDocument', 'FeedLineCount', 'FieldName', 'FieldNumber', 'FieldSize', 'FieldType', 'FileName', 'FillSlipDocumentWithUnfiscalInfo', 'FindDevice',
    'FinishDocument', 'FinishDocumentMode', 'FirstDocumentNumber', 'FirstLineNumber', 'FirstSessionDate', 'FirstSessionNumber', 'FiscalReportForDatesRange', 'FiscalReportForSessionRange', 'FiscalSign', 'FiscalSignAsString',
    'FiscalSignOFD', 'Fiscalization', 'FiscalizationWithLongRNM', 'FontCount', 'FontHashHex', 'FontType', 'FreeMemorySize', 'FreeRecordInFM', 'FreeRegistration', 'GenerateMonoToken', 'GetActiveLD', 'GetCashAcceptorRegisters',
    'GetCashAcceptorStatus', 'GetCashReg', 'GetCashRegEx', 'GetCloudCashdeskParams', 'GetCommandParams', 'GetCountLD', 'GetData', 'GetDeviceFunction', 'GetDeviceMetrics', 'GetECRParams', 'GetECRPrinterStatus', 'GetECRStatus',
    'GetEKLZActivizationResult', 'GetEKLZCode1Report', 'GetEKLZCode1Status', 'GetEKLZCode2Report', 'GetEKLZCode2Status', 'GetEKLZCode3Report', 'GetEKLZData', 'GetEKLZDepartmentReportInDatesRange', 'GetEKLZDepartmentReportInSessionsRange',
    'GetEKLZDocument', 'GetEKLZJournal', 'GetEKLZSerialNumber', 'GetEKLZSessionReportInDatesRange', 'GetEKLZSessionReportInSessionsRange', 'GetEKLZSessionTotal', 'GetEKLZVersion', 'GetExchangeParam', 'GetFMRecordsSum', 'GetFieldStruct',
    'GetFiscalizationParameters', 'GetFontMetrics', 'GetFreeLDNumber', 'GetIBMStatus', 'GetInterval', 'GetKKTLicenseByNumber', 'GetLastFMRecordDate', 'GetLiterSumCounter', 'GetLongSerialNumberAndLongRNM', 'GetMFPCode3Status',
    'GetOperationReg', 'GetParamLD', 'GetPortNames', 'GetQuantityFactor', 'GetRKStatus', 'GetRKStatusDescription', 'GetRangeDatesAndSessions', 'GetShortECRStatus', 'GetShortIBMStatus', 'GetShortReportInDatesRange', 'GetShortReportInSessionRange',
    'GetSummFactor', 'GetTableStruct', 'GetTagAsTLV', 'GetWareBaseCashRegs', 'Get_AccType', 'Get_AddTaxesEnabled', 'Get_Address', 'Get_AutoEoD', 'Get_AutoOFDExchange', 'Get_BarcodeAlignments', 'Get_BarcodeTypes', 'Get_BatteryCondition',
    'Get_CPLog', 'Get_CPLogFile', 'Get_CapOpenCheck', 'Get_CardPayEnabled', 'Get_CardPayType', 'Get_CheckResult', 'Get_ComLogFile', 'Get_ComLogOnlyErrors', 'Get_CurrentDozeInMilliliters', 'Get_CurrentDozeInMoney', 'Get_DelayOnDisconnect',
    'Get_DiscountName', 'Get_DocumentData', 'Get_DozeInMilliliters', 'Get_Doze']
