"""add_table_rooms

Revision ID: 2a988f1a8e4c
Revises: 166846aee3cd
Create Date: 2025-10-06 16:36:16.173342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a988f1a8e4c'
down_revision: Union[str, Sequence[str], None] = '166846aee3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'rooms', ['room_id'], ['id'])
    op.drop_column('transactions', 'room_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('room_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'room_id')
    op.drop_table('rooms')
    # ### end Alembic commands ###
