"""code

Revision ID: 44848ae9c74a
Revises: b87d81909d4d
Create Date: 2025-10-16 17:00:15.557990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44848ae9c74a'
down_revision: Union[str, Sequence[str], None] = 'b87d81909d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fines', sa.Column('code', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'code')
    op.drop_column('fines', 'code')
    # ### end Alembic commands ###
