"""rename field model

Revision ID: 6ab12302ba82
Revises: 852ac083956c
Create Date: 2025-10-08 13:25:28.778093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab12302ba82'
down_revision: Union[str, Sequence[str], None] = '852ac083956c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screensaver_settings', sa.Column('sound_is_enable', sa.Boolean(), nullable=False))
    op.drop_column('screensaver_settings', 'sound_enable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screensaver_settings', sa.Column('sound_enable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('screensaver_settings', 'sound_is_enable')
    # ### end Alembic commands ###
