"""screensaver

Revision ID: 852ac083956c
Revises: 07ce43a865cd
Create Date: 2025-10-08 11:26:43.457873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852ac083956c'
down_revision: Union[str, Sequence[str], None] = '07ce43a865cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screensaver_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('sound_is_enable', sa.Boolean(), nullable=True),
    sa.Column('time_show_image', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screensaver_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('sound_enable', sa.Boolean(), nullable=False),
    sa.Column('time_show_image', sa.Integer(), nullable=False),
    sa.Column('idle_time', sa.Integer(), nullable=False),
    sa.Column('show_clock', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screensaver_settings')
    op.drop_table('screensaver_files')
    # ### end Alembic commands ###
