"""init

Revision ID: 984c1b30785d
Revises: 27197cc09cba
Create Date: 2025-10-14 10:52:36.340751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984c1b30785d'
down_revision: Union[str, Sequence[str], None] = '27197cc09cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('count_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screensaver_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('sound_is_enable', sa.Boolean(), nullable=True),
    sa.Column('time_show_image', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screensaver_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('sound_is_enable', sa.Boolean(), nullable=False),
    sa.Column('time_show_image', sa.Integer(), nullable=False),
    sa.Column('idle_time', sa.Integer(), nullable=False),
    sa.Column('show_clock', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_countable', sa.Boolean(), nullable=False),
    sa.Column('is_duration', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=30), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('room_building', sa.Integer(), nullable=False),
    sa.Column('count_days', sa.Integer(), nullable=False),
    sa.Column('room_day_price', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_fines',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('fine_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'fine_id')
    )
    op.create_table('transaction_services',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_services')
    op.drop_table('transaction_fines')
    op.drop_table('transactions')
    op.drop_table('services')
    op.drop_table('screensaver_settings')
    op.drop_table('screensaver_files')
    op.drop_table('room_prices')
    op.drop_table('guests')
    op.drop_table('fines')
    # ### end Alembic commands ###
