"""fix

Revision ID: b87d81909d4d
Revises: 9eb6d5ce2e2c
Create Date: 2025-10-14 13:57:04.835971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87d81909d4d'
down_revision: Union[str, Sequence[str], None] = '9eb6d5ce2e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'count_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'count_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
