"""init

Revision ID: d3eaf1ebfddd
Revises: 
Create Date: 2025-09-18 17:21:32.231445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3eaf1ebfddd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_functions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('function_name', sa.String(), nullable=False),
    sa.Column('endpoint_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_name'),
    sa.UniqueConstraint('function_name')
    )
    op.create_index(op.f('ix_terminal_functions_id'), 'terminal_functions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('cookies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cookies_id'), 'cookies', ['id'], unique=False)
    op.create_table('user_functions_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('terminal_function_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['terminal_function_id'], ['terminal_functions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_functions_map_id'), 'user_functions_map', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_functions_map_id'), table_name='user_functions_map')
    op.drop_table('user_functions_map')
    op.drop_index(op.f('ix_cookies_id'), table_name='cookies')
    op.drop_table('cookies')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_terminal_functions_id'), table_name='terminal_functions')
    op.drop_table('terminal_functions')
    # ### end Alembic commands ###
