"""add module_name in terminal_functions

Revision ID: f3d01f1a6ee1
Revises: d3eaf1ebfddd
Create Date: 2025-09-23 10:06:57.122426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d01f1a6ee1'
down_revision: Union[str, Sequence[str], None] = 'd3eaf1ebfddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terminal_functions', sa.Column('module_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminal_functions', 'module_name')
    # ### end Alembic commands ###
