from fastapi import status

from api.DTO.factories.router_factory import RouteDTO
from modules.fiscal.endpoints.receipt_endpoints import *


RECEIPT_ROUTES = [
    # Базовые операции с чеками
    RouteDTO(
        path="/open",
        endpoint=open_receipt,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Открыть чек",
        description="Открыть новый чек (продажа, возврат, покупка, коррекция)",
        responses={},
    ),
    RouteDTO(
        path="/cancel",
        endpoint=cancel_receipt,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Отменить чек",
        description="Отменить открытый чек без печати",
        responses={},
    ),
    RouteDTO(
        path="/registration",
        endpoint=registration,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Зарегистрировать позицию",
        description="Добавить товар/услугу в открытый чек",
        responses={},
    ),
    RouteDTO(
        path="/payment",
        endpoint=payment,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Зарегистрировать оплату",
        description="Добавить оплату в открытый чек",
        responses={},
    ),
    RouteDTO(
        path="/tax",
        endpoint=receipt_tax,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Зарегистрировать налог на чек",
        description="Зарегистрировать сумму налога на чек",
        responses={},
    ),
    RouteDTO(
        path="/total",
        endpoint=receipt_total,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Зарегистрировать итог",
        description="Зарегистрировать итоговую сумму чека (необязательно)",
        responses={},
    ),
    RouteDTO(
        path="/close",
        endpoint=close_receipt,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Закрыть чек",
        description="Закрыть и напечатать чек",
        responses={},
    ),
    RouteDTO(
        path="/check-closed",
        endpoint=check_document_closed,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Проверить закрытие чека",
        description="ВАЖНО! Проверить, что чек успешно закрылся и напечатался",
        responses={},
    ),
    RouteDTO(
        path="/continue-print",
        endpoint=continue_print,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Допечатать документ",
        description="Допечатать чек, если он закрылся, но не напечатался",
        responses={},
    ),

    # Операции с кодами маркировки (ФФД 1.2)
    RouteDTO(
        path="/marking/begin-validation",
        endpoint=begin_marking_code_validation,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Начать проверку КМ",
        description="Начать проверку кода маркировки (синхронный/асинхронный режим)",
        responses={},
    ),
    RouteDTO(
        path="/marking/validation-status",
        endpoint=get_marking_code_validation_status,
        response_model=BaseResponseDTO,
        methods=["GET"],
        status_code=status.HTTP_200_OK,
        summary="Статус проверки КМ",
        description="Получить статус проверки кода маркировки",
        responses={},
    ),
    RouteDTO(
        path="/marking/accept",
        endpoint=accept_marking_code,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Подтвердить реализацию КМ",
        description="Подтвердить реализацию товара с кодом маркировки",
        responses={},
    ),
    RouteDTO(
        path="/marking/decline",
        endpoint=decline_marking_code,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Отказаться от реализации КМ",
        description="Отказаться от реализации товара с кодом маркировки",
        responses={},
    ),
    RouteDTO(
        path="/marking/cancel-validation",
        endpoint=cancel_marking_code_validation,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Отменить проверку КМ",
        description="Отменить текущую проверку кода маркировки",
        responses={},
    ),
    RouteDTO(
        path="/marking/clear-validation-result",
        endpoint=clear_marking_code_validation_result,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Очистить таблицу КМ",
        description="Очистить таблицу проверенных кодов маркировки в ФН",
        responses={},
    ),
    RouteDTO(
        path="/marking/check-validations-ready",
        endpoint=check_marking_code_validations_ready,
        response_model=BaseResponseDTO,
        methods=["GET"],
        status_code=status.HTTP_200_OK,
        summary="Проверить готовность КМ",
        description="Проверить завершение всех фоновых проверок КМ",
        responses={},
    ),
    RouteDTO(
        path="/sales-notice",
        endpoint=write_sales_notice,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Передать данные уведомления",
        description="Передать данные уведомления о реализации маркированного товара",
        responses={},
    ),
    RouteDTO(
        path="/marking/update-fnm-keys",
        endpoint=update_fnm_keys,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Обновить ключи ФН-М",
        description="Обновить ключи проверки ФН-М (только ККТ 5.X, ФФД ≥ 1.2)",
        responses={},
    ),
    RouteDTO(
        path="/marking/ping-server",
        endpoint=ping_marking_server,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Проверить сервер ИСМ",
        description="Начать проверку связи с сервером ИСМ",
        responses={},
    ),
    RouteDTO(
        path="/marking/server-status",
        endpoint=get_marking_server_status,
        response_model=BaseResponseDTO,
        methods=["GET"],
        status_code=status.HTTP_200_OK,
        summary="Статус сервера ИСМ",
        description="Получить статус проверки сервера ИСМ",
        responses={},
    ),
]
