from fastapi import status

from api.DTO.factories.router_factory import RouteDTO
from modules.fiscal.endpoints.receipt_endpoints import *


RECEIPT_ROUTES = [
    # Базовые операции с чеками
    RouteDTO(
        path="/open",
        endpoint=open_receipt,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Открыть чек",
        description="Открыть новый чек (продажа, возврат, покупка, коррекция)",
        responses={},
    ),
    RouteDTO(
        path="/cancel",
        endpoint=cancel_receipt,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Отменить чек",
        description="Отменить открытый чек.\n\nПараметр clear_marking_table позволяет не очищать таблицу КМ драйвера, если планируется сразу провести точно такой же чек.",
        responses={},
    ),
    RouteDTO(
        path="/registration",
        endpoint=registration,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Зарегистрировать позицию",
        description="Зарегистрировать позицию в чеке.\n\nПоддерживает:\n- Простые позиции с НДС\n- Позиции с маркировкой (ФФД < 1.2 и ФФД ≥ 1.2)\n- Позиции с агентами и поставщиками\n- Позиции с кодами товара (тег 1163)\n- Позиции с отраслевым реквизитом (тег 1260)",
        responses={},
    ),
    RouteDTO(
        path="/payment",
        endpoint=payment,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Зарегистрировать оплату",
        description="Зарегистрировать оплату чека.\n\nПоддерживаемые способы оплаты:\n- Наличными (0)\n- Безналичными (1) - с возможностью передачи дополнительных сведений\n- Предварительная оплата/аванс (2)\n- Последующая оплата/кредит (3)\n- Иная форма оплаты (4)\n- Способы расчета №6-10 (5-9)\n\nДля безналичной оплаты можно передать дополнительные сведения через параметры electronically_*.",
        responses={},
    ),
    RouteDTO(
        path="/tax",
        endpoint=receipt_tax,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Зарегистрировать налог на чек",
        description="Зарегистрировать налог на чек.\n\nИспользуется когда при регистрации позиций был установлен параметр use_only_tax_type=true.",
        responses={},
    ),
    RouteDTO(
        path="/total",
        endpoint=receipt_total,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Зарегистрировать итог",
        description="Зарегистрировать итог чека.\n\nНеобязательный метод. Если не вызвать, сумма чека будет посчитана автоматически. Можно зарегистрировать итог с округлением в пределах ±99 копеек.",
        responses={},
    ),
    RouteDTO(
        path="/close",
        endpoint=close_receipt,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Закрыть чек",
        description="Закрыть чек.\n\nЕсли чек не полностью оплачен, будет автоматически доплачен указанным способом оплаты (по умолчанию наличными).\n\nВАЖНО: После закрытия чека обязательно вызовите check_document_closed() для проверки успешности операции!",
        responses={},
    ),
    RouteDTO(
        path="/check-closed",
        endpoint=check_document_closed,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Проверить закрытие чека",
        description="Проверить закрытие документа.\n\nКРИТИЧЕСКИ ВАЖНЫЙ метод! Проверяет:\n- Закрылся ли документ в ФН\n- Напечатался ли документ на чековой ленте\n\nЕсли документ закрылся, но не напечатался - вызовите continue_print().\nЕсли документ не закрылся - отмените чек и сформируйте заново.\n\nЕсли метод вернул ошибку - нельзя выключать ПК, нужно восстановить работу ККТ!",
        responses={},
    ),
    RouteDTO(
        path="/continue-print",
        endpoint=continue_print,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Допечатать документ",
        description="Допечатать фискальный документ.\n\nИспользуется когда документ закрылся в ФН, но не напечатался на чековой ленте (например, закончилась бумага).",
        responses={},
    ),

    # Операции с кодами маркировки (ФФД 1.2)
    RouteDTO(
        path="/marking/begin-validation",
        endpoint=begin_marking_code_validation,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Начать проверку КМ",
        description="Начать проверку кода маркировки (синхронный/асинхронный режим)",
        responses={},
    ),
    RouteDTO(
        path="/marking/validation-status",
        endpoint=get_marking_code_validation_status,
        response_model=BaseResponseDTO,
        methods=["GET"],
        status_code=status.HTTP_200_OK,
        summary="Статус проверки КМ",
        description="Получить статус проверки кода маркировки",
        responses={},
    ),
    RouteDTO(
        path="/marking/accept",
        endpoint=accept_marking_code,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Подтвердить реализацию КМ",
        description="Подтвердить реализацию товара с кодом маркировки",
        responses={},
    ),
    RouteDTO(
        path="/marking/decline",
        endpoint=decline_marking_code,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Отказаться от реализации КМ",
        description="Отказаться от реализации товара с кодом маркировки",
        responses={},
    ),
    RouteDTO(
        path="/marking/cancel-validation",
        endpoint=cancel_marking_code_validation,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Отменить проверку КМ",
        description="Отменить текущую проверку кода маркировки",
        responses={},
    ),
    RouteDTO(
        path="/marking/clear-validation-result",
        endpoint=clear_marking_code_validation_result,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Очистить таблицу КМ",
        description="Очистить таблицу проверенных кодов маркировки в ФН",
        responses={},
    ),
    RouteDTO(
        path="/marking/check-validations-ready",
        endpoint=check_marking_code_validations_ready,
        response_model=BaseResponseDTO,
        methods=["GET"],
        status_code=status.HTTP_200_OK,
        summary="Проверить готовность КМ",
        description="Проверить завершение всех фоновых проверок КМ",
        responses={},
    ),
    RouteDTO(
        path="/sales-notice",
        endpoint=write_sales_notice,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Передать данные уведомления",
        description="Передать данные уведомления о реализации маркированного товара",
        responses={},
    ),
    RouteDTO(
        path="/marking/update-fnm-keys",
        endpoint=update_fnm_keys,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Обновить ключи ФН-М",
        description="Обновить ключи проверки ФН-М (только ККТ 5.X, ФФД ≥ 1.2)",
        responses={},
    ),
    RouteDTO(
        path="/marking/ping-server",
        endpoint=ping_marking_server,
        response_model=BaseResponseDTO,
        methods=["POST"],
        status_code=status.HTTP_200_OK,
        summary="Проверить сервер ИСМ",
        description="Начать проверку связи с сервером ИСМ",
        responses={},
    ),
    RouteDTO(
        path="/marking/server-status",
        endpoint=get_marking_server_status,
        response_model=BaseResponseDTO,
        methods=["GET"],
        status_code=status.HTTP_200_OK,
        summary="Статус сервера ИСМ",
        description="Получить статус проверки сервера ИСМ",
        responses={},
    ),
]
